GrantItems/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('items.urls')),
    path('auth/',include('grant_auth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

grant_auth/urls.py
from django.urls import path
from . import views

app_name = 'grant_auth'

urlpatterns=[
    path('login/', views.grant_login, name='login'),
    path('register/', views.register, name='register'),
    path('captcha', views.send_email_captcha, name='captcha'),
    path('logout/', views.grant_logout, name='logout'),
]

items/urls.py
from django.urls import path


from . import views

app_name = 'items'

urlpatterns = [
    path('', views.index, name='index'),
    path('index', views.login_index, name='login_index'),
    path('items/search', views.search, name='search'),
    path('items/add', views.item_add, name='item_add'),
    path('items/modify/<int:item_id>/', views.item_modify, name='item_modify'),
    path('items/show_all', views.show_all, name='show_all'),
    path('items/show_type/<int:type_id>/', views.show_type, name='show_type'),
    path('items/show_status/<int:status_id>/', views.show_status, name='show_status'),
    path('items/show_detail/<int:item_id>/', views.show_detail, name='show_detail'),
    path('items/remove/<int:item_id>/', views.item_remove, name='item_remove'),
    path('items/delete/<int:item_id>/', views.item_delete, name='item_delete'),
    path('items/timeline', views.item_timeline, name='item_timeline'),
    path('items/expired', views.item_expired, name='item_expired'),
]

items/models.py
from django.db import models
from django.template.context_processors import request


class ItemCategory(models.Model):
    name = models.CharField(max_length=100, verbose_name='物品类别')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '物品类别'
        verbose_name_plural = verbose_name

class ItemStatus(models.Model):
    name = models.CharField(max_length=100, verbose_name='物品状态')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '物品状态'
        verbose_name_plural = verbose_name

class Item(models.Model):
    name = models.CharField(max_length=100, verbose_name='物品名称')
    count = models.IntegerField(verbose_name='数量')
    type = models.ForeignKey(ItemCategory, on_delete=models.CASCADE, verbose_name='物品类别')
    status = models.ForeignKey(ItemStatus, on_delete=models.CASCADE, verbose_name='物品状态')
    # 0:正常 1:预购 2:待出 3:已出
    is_consumable = models.BooleanField(verbose_name='是否消耗品',default=False)
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='价格',blank=True)
    image = models.ImageField(upload_to='items/', verbose_name='图片',blank=True,default='static/images/logo.png')
    overdue = models.DateField(verbose_name='过期时间',blank=True,null=True)
    link = models.URLField(verbose_name='链接',blank=True)
    description = models.TextField(verbose_name='描述',blank=True)
    owner = models.ForeignKey('auth.User', on_delete=models.CASCADE, verbose_name='所有者')
    create_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '物品'
        verbose_name_plural = verbose_name
        ordering = ['-create_time']

items/forms.py
from django import forms

class ItemForm(forms.ModelForm):
    name = forms.CharField(max_length=100, min_length=1)
    count = forms.IntegerField()
    type = forms.IntegerField()
    status = forms.IntegerField()
    is_consumable = forms.BooleanField()
    price = forms.DecimalField()
    image = forms.ImageField()
    overdue = forms.DateField(required=False,widget=forms.DateInput(attrs={'type': 'date'}))
    link = forms.URLField()
    description = forms.Textarea()
    owner = forms.IntegerField()

items/views.py
from Tools.scripts.make_ctype import method
from django.db.models import Q
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.decorators.http import require_http_methods, require_POST, require_GET
from django.db.models import Count
from datetime import timedelta
from django.utils import timezone

from items.models import ItemCategory, ItemStatus, Item


# Create your views here.
def index(request):
    return render(request, 'index.html')


@login_required(login_url=reverse_lazy('grant_auth:login'))
def login_index(request):
    today = timezone.now().date()
    one_month_later = today + timedelta(days=30)

    expired_items = Item.objects.filter(owner=request.user, overdue__lt=today, status_id__in=[1, 3]).order_by(
        'overdue')[:5]
    expiring_soon_items = Item.objects.filter(owner=request.user, overdue__range=(today, one_month_later),
                                              status_id__in=[1, 3]).order_by(
        'overdue')[:5]
    pre_purchase_items = Item.objects.filter(owner=request.user, status_id=2).order_by('overdue')[
                         :5]  # Assuming status_id=2 represents pre-purchase items
    category_counts = Item.objects.filter(owner=request.user).values('type__name').annotate(count=Count('id')).order_by(
        'type__name')
    status_counts = Item.objects.filter(owner=request.user).values('status__name').annotate(count=Count('id')).order_by(
        'status__name')

    context = {
        'expired_items': expired_items,
        'expiring_soon_items': expiring_soon_items,
        'pre_purchase_items': pre_purchase_items,
        'today': today,
        'category_counts': list(category_counts),
        'status_counts': list(status_counts)
    }
    return render(request, 'login_index.html', context=context)


@require_http_methods(['GET', 'POST'])
@login_required(login_url=reverse_lazy('grant_auth:login'))
def item_add(request):
    if request.method == 'GET':
        categories = ItemCategory.objects.all()
        status = ItemStatus.objects.all()
        context = {
            'categories': categories,
            'status': status
        }
        return render(request, 'item_add.html', context=context)
    else:
        name = request.POST.get('name')
        description = request.POST.get('description')
        type = request.POST.get('type')
        status = request.POST.get('status')
        is_consumable = request.POST.get('is_consumable') == 'true'
        price = request.POST.get('price')
        count = request.POST.get('count')
        image = request.FILES.get('image')
        overdue = request.POST.get('overdue') or None
        link = request.POST.get('link')
        owner = request.user

        image_path = None
        if image:
            image_path = 'media/items/' + image.name
            with open(image_path, 'wb') as dest:
                for chunk in image.chunks():
                    dest.write(chunk)
        Item.objects.create(name=name, description=description,
                            type_id=type, status_id=status, is_consumable=is_consumable,
                            image=image_path, price=price,
                            count=count, overdue=overdue, link=link, owner=owner)
        return JsonResponse({'code': 200, 'msg': '发布成功'})


@require_http_methods(['GET', 'POST'])
@login_required(login_url=reverse_lazy('grant_auth:login'))
def show_all(request):
    items = Item.objects.filter(owner=request.user, status_id__in=[1, 2, 3]).order_by('type_id').order_by('status_id')
    context = {
        'items': items
    }
    return render(request, 'show_all.html', context=context)


@require_http_methods(['GET', 'POST'])
@login_required(login_url=reverse_lazy('grant_auth:login'))
def show_type(request, type_id):
    items = Item.objects.filter(owner=request.user, type_id=type_id, status_id__in=[1, 2, 3]).order_by('status_id')
    context = {
        'items': items
    }
    return render(request, 'show_all.html', context=context)


@require_http_methods(['GET', 'POST'])
@login_required(login_url=reverse_lazy('grant_auth:login'))
def show_status(request, status_id):
    items = Item.objects.filter(owner=request.user, status_id=status_id).order_by('type_id')
    context = {
        'items': items
    }
    return render(request, 'show_all.html', context=context)


def show_detail(request, item_id):
    item = Item.objects.get(id=item_id)
    context = {
        'item': item
    }
    return render(request, 'show_detail.html', context=context)


@require_http_methods(['GET', 'POST'])
@login_required(login_url=reverse_lazy('grant_auth:login'))
def item_modify(request, item_id):
    if request.method == 'GET':
        categories = ItemCategory.objects.all()
        status = ItemStatus.objects.all()
        context = {
            'categories': categories,
            'status': status,
            'item': Item.objects.get(id=item_id)
        }
        return render(request, 'item_modify.html', context=context)
    else:
        print(request.POST)
        name = request.POST.get('name')
        description = request.POST.get('description')
        type = request.POST.get('type')
        status = request.POST.get('status')
        is_consumable = request.POST.get('is_consumable') == 'true'
        price = request.POST.get('price')
        count = request.POST.get('count')
        image = request.FILES.get('image')
        overdue = request.POST.get('overdue') or None
        link = request.POST.get('link')
        owner = request.user

        if image:
            image_path = 'media/items/' + image.name
            with open(image_path, 'wb') as dest:
                for chunk in image.chunks():
                    dest.write(chunk)
            Item.objects.filter(id=item_id).update(name=name, description=description,
                                                   type_id=type, status_id=status, is_consumable=is_consumable,
                                                   image=image_path, price=price,
                                                   count=count, overdue=overdue, link=link, owner=owner)
        else:
            Item.objects.filter(id=item_id).update(name=name, description=description,
                                                   type_id=type, status_id=status, is_consumable=is_consumable,
                                                   price=price, count=count, overdue=overdue, link=link, owner=owner)
        return JsonResponse({'code': 200, 'msg': '修改成功！', 'item_id': item_id})


def item_remove(request, item_id):
    Item.objects.filter(id=item_id).update(status_id=4)
    return redirect('items:show_all')


def item_delete(request, item_id):
    Item.objects.filter(id=item_id).delete()
    return redirect('items:show_all')


@require_http_methods(['GET', 'POST'])
@login_required(login_url=reverse_lazy('grant_auth:login'))
def item_timeline(request):
    items = Item.objects.filter(owner=request.user, overdue__isnull=False, status_id__in=[1, 3]).order_by('overdue')
    context = {
        'items': items,
        'today': timezone.now().date()
    }
    return render(request, 'item_timeline.html', context=context)


@require_http_methods(['GET', 'POST'])
@login_required(login_url=reverse_lazy('grant_auth:login'))
def item_expired(request):
    items = Item.objects.filter(owner=request.user, overdue__lt=timezone.now().date(), status_id__in=[1, 3]).order_by(
        'overdue')
    context = {
        'items': items,
        'today': timezone.now().date()
    }
    return render(request, 'show_all.html', context=context)


@require_http_methods(['GET', 'POST'])
@login_required(login_url=reverse_lazy('grant_auth:login'))
@require_GET
def search(request):
    q = request.GET.get('q')
    items = Item.objects.filter(Q(name__icontains=q) | Q(description__icontains=q), owner=request.user)
    return render(request, 'show_all.html', context={'items': items})

items/templates/index.html
{% extends 'base.html' %}

{% block main %}
    <div class="px-4 py-5 my-5 text-center">
        <img class="d-block mx-auto mb-4" src="{% static 'images/logo.png' %}" alt="" width="72" height="57">
        <h1 class="display-5 fw-bold text-body-emphasis">GrantItems 格物</h1>
        <div class="col-lg-6 mx-auto">
            <p class="lead mb-4">格物：个人物品管理系统助你轻松分类、追踪和管理所有物品。</p>
            <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
                <a type="button" class="btn btn-primary btn-lg px-4 gap-3" href="{% url 'grant_auth:login' %}">登陆</a>
                <a type="button" class="btn btn-outline-secondary btn-lg px-4" href="{% url 'grant_auth:register' %}">注册</a>
            </div>
        </div>
    </div>
{% endblock %}

items/templates/item_add.html
{% extends 'base.html' %}

{% block title %}添加物品{% endblock %}

{% block head %}
    <!-- 自定义样式 -->
    <style>
        .form-control:focus {
            border-color: #28a745;
            box-shadow: 0 0 5px rgba(40, 167, 69, 0.5);
        }

        .btn-success:hover {
            background-color: #218838;
            border-color: #1e7e34;
        }
    </style>
    <script src='{% static 'js/add_item.js' %}'></script>
{% endblock %}

{% block main %}
        <div class="card mx-auto" style="max-width: 800px;">
            <div class="card-header text-center bg-primary text-white">
                <h2>添加物品</h2>
            </div>
            <div class="card-body">
                <form action="{% url 'items:item_add' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <!-- 使用网格系统 -->
                    <div class="row mb-3">
                        <div class="col-md-6">
                            <label for="name" class="form-label">物品名称</label>
                            <input type="text" class="form-control" name="name" id="name" placeholder="请输入物品名称">
                        </div>
                        <div class="col-md-6">
                            <label for="category-select" class="form-label">分类</label>
                            <select name="category" class="form-select" id="category-select">
                                {% for category in categories %}
                                    <option value="{{ category.id }}">{{ category.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col-md-6">
                            <label for="count" class="form-label">数量</label>
                            <input type="number" class="form-control" name="count" id="count" placeholder="请输入数量">
                        </div>
                        <div class="col-md-6">
                            <label for="price" class="form-label">价格</label>
                            <input type="number" class="form-control" name="price" id="price" placeholder="请输入价格">
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col-md-6">
                            <label for="status-select" class="form-label">状态</label>
                            <select name="status" class="form-select" id="status-select">
                                {% for status in status %}
                                    <option value="{{ status.id }}">{{ status.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="col-md-6">
                            <label for="overdue" class="form-label">过期时间</label>
                            <input type="date" class="form-control" name="overdue" id="overdue">
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col-md-6">
                            <label for="link" class="form-label">链接</label>
                            <input type="url" class="form-control" name="link" id="link" placeholder="请输入链接">
                        </div>
                        <div class="col-md-6">
                            <label for="image" class="form-label">图片</label>
                            <input type="file" class="form-control" name="image" id="image">
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="d-flex align-items-center">
                            <label class="form-label me-2 mb-0">是否为消耗品</label>
                            <div class="form-check form-switch">
                                <input class="form-check-input" type="checkbox" name="is_consumable" id="is_consumable">
                                <label class="form-check-label" for="is_consumable">是</label>
                            </div>
                        </div>
                    </div>
                    <!-- 备注 -->
                    <div class="mb-3">
                        <label for="description" class="form-label">备注</label>
                        <textarea class="form-control" name="description" id="description" rows="3"
                                  placeholder="请输入备注"></textarea>
                    </div>
                    <!-- 提交按钮 -->
                    <div class="text-end">
                        <button class="btn btn-success btn-lg" id="submit-btn">
                            <i class="bi bi-plus-circle"></i> 添加
                        </button>
                    </div>
                </form>
            </div>
        </div>

{% endblock %}

items/templates/item_modify.html
{% extends 'base.html' %}

{% block title %}添加物品{% endblock %}

{% block head %}
    <!-- 自定义样式 -->
    <style>
        .form-control:focus {
            border-color: #28a745;
            box-shadow: 0 0 5px rgba(40, 167, 69, 0.5);
        }

        .btn-success:hover {
            background-color: #218838;
            border-color: #1e7e34;
        }
    </style>
    <script src='{% static 'js/modify_item.js' %}'></script>
{% endblock %}

{% block main %}
    <div class="container">
        <div class="card mx-auto" style="max-width: 800px;">
            <div class="card-header text-center bg-primary text-white">
                <h2>修改物品</h2>
            </div>
            <div class="card-body">
                <form action="{% url 'items:item_modify' item_id=item.id %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <!-- 使用网格系统 -->
                    <div class="row mb-3">
                        <div class="col-md-6">
                            <label for="name" class="form-label">物品名称</label>
                            <input type="text" class="form-control" name="name" id="name" value="{{ item.name }}"
                                   placeholder="{{ item.name }}" required>
                        </div>
                        <div class="col-md-6">
                            <label for="category-select" class="form-label">分类</label>
                            <select name="category" class="form-select" id="category-select">
                                {% for category in categories %}
                                    <option value="{{ category.id }}" {% if category.id == item.type_id %}
                                            selected
                                    {% endif %} >{{ category.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col-md-6">
                            <label for="count" class="form-label">数量</label>
                            <input type="number" class="form-control" name="count" id="count" value="{{ item.count }}"
                                   placeholder="{{ item.count }}" required>
                        </div>
                        <div class="col-md-6">
                            <label for="price" class="form-label">价格</label>
                            <input type="number" class="form-control" name="price" id="price" value="{{ item.price }}"
                                   placeholder="{{ item.price }}">
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col-md-6">
                            <label for="status-select" class="form-label">状态</label>
                            <select name="status" class="form-select" id="status-select">
                                {% for status in status %}
                                    <option value="{{ status.id }}" {% if status.id == item.status_id %}
                                            selected
                                    {% endif %} >{{ status.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="col-md-6">
                            <label for="overdue" class="form-label">过期时间</label>
                            <input type="date" class="form-control" name="overdue" id="overdue" value="{{ item.overdue|date:'Y-m-d' }}">
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col-md-6">
                            <label for="link" class="form-label">链接</label>
                            <input type="url" class="form-control" name="link" id="link" placeholder="{{ item.link }}" value="{{ item.link }}">
                        </div>
                        <div class="col-md-6">
                            <label for="image" class="form-label">图片</label>
                            <input type="file" class="form-control" name="image" id="image">
                        </div>
                    </div>
                    <div class="row mb-3">
                            <div class="d-flex align-items-center">
                                <label class="form-label me-2 mb-0">是否为消耗品</label>
                                <div class="form-check form-switch">
                                    <input class="form-check-input" type="checkbox" name="is_consumable" id="is_consumable">
                                    <label class="form-check-label" for="is_consumable">是</label>
                                </div>
                            </div>
                    </div>
                    <!-- 备注 -->
                    <div class="mb-3">
                        <label for="description" class="form-label">备注</label>
                        <textarea class="form-control" name="description" id="description" rows="3"
                                  >{{ item.description }}</textarea>
                    </div>
                    <!-- 提交按钮 -->
                    <div class="text-end">
                        <button class="btn btn-success btn-lg" id="submit-btn">
                            <i class="bi bi-plus-circle"></i> 修改
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

items/templates/item_timeline.html
{% extends 'base.html' %}
{% load date_diff %}

{% block title %}
    过期时间线
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/timeline.css' %}">
    <script src="{% static 'js/timeline.js' %}"></script>
{% endblock %}

{% block main %}
    <div class="container-second">
        {% for item in items %}
            <p class="{% if item.overdue < today %}overdue{% else %}not-overdue{% endif %}">
                {{ item.overdue|date:'Y-m-d' }} — {{ item.name }} ——
                {% if item.overdue < today %}
                    (已过期 {{ today|date_diff:item.overdue }} 天)
                {% else %}
                    (还有 {{ item.overdue|date_diff:today }} 天过期)
                {% endif %}
            </p>
            {% if not forloop.last %}
                <div class="vertical-bar"></div>
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}

items/templates/login_index.html
{% extends 'base.html' %}
{% load date_diff %}

{% block head %}
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="{% static 'js/login_index.js' %}"></script>
    <script>
        window.categoryCounts = {{ category_counts|safe }};
        window.statusCounts = {{ status_counts|safe }};
    </script>
{% endblock %}

{% block main %}
    <div class="row">
        <div class="col-md-8">
            <div class="row">
                <div class="col-md-6 d-flex align-items-center">
                    <canvas id="categoryChart" class="w-100" style="height: 400px;"></canvas>
                </div>
                <div class="col-md-6 d-flex align-items-center">
                    <canvas id="categoryPieChart" class="w-100" style="height: 400px;"></canvas>
                </div>
            </div>
            <div class="row mt-4">
                <div class="col-md-6 d-flex align-items-center">
                    <canvas id="statusChart" class="w-100" style="height: 400px;"></canvas>
                </div>
                <div class="col-md-6 d-flex align-items-center">
                    <canvas id="statusPieChart" class="w-100" style="height: 400px;"></canvas>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="container mt-4">
                <h2>已过期</h2>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th scope="col">名称</th>
                            <th scope="col">状态</th>
                            <th scope="col">时间</th>
                            <th scope="col">过期信息</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in expired_items %}
                        <tr>
                            <td><a href="{% url 'items:show_detail' item_id=item.id %}" style="text-decoration: none">{{ item.name }}</td>
                            <td>{{ item.status.name }}</td>
                            <td>{{ item.overdue|date:"Y-m-d" }}</td>
                            <td>已过{{ today|date_diff:item.overdue }}天</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="container mt-4">
                <h2>即将过期</h2>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th scope="col">名称</th>
                            <th scope="col">状态</th>
                            <th scope="col">时间</th>
                            <th scope="col">过期信息</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in expiring_soon_items %}
                        <tr>
                            <td><a href="{% url 'items:show_detail' item_id=item.id %}" style="text-decoration: none">{{ item.name }}</td>
                            <td>{{ item.status.name }}</td>
                            <td>{{ item.overdue|date:"Y-m-d" }}</td>
                            <td>还剩{{ item.overdue|date_diff:today }}天</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="container mt-4">
                <h2>预购</h2>
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th scope="col">名称</th>
                        <th scope="col">价格</th>
                        <th scope="col">种类</th>
                        <th scope="col">状态</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for item in pre_purchase_items %}
                        <tr>
                            <td><a href="{% url 'items:show_detail' item_id=item.id %}" style="text-decoration: none">{{ item.name }}</td>
                            <td>{{ item.price }}</td>
                            <td>{{ item.type.name }}</td>
                            <td>{{ item.status.name }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

items/templates/show_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ item.name }}
{% endblock %}

{% block main %}
    <div class="card" style="width: 100%; aspect-ratio: 2/1">
        <div class="row g-0" style="height: 100%;">
            <div class="col-md-6" style="height: 100%;">
                {% if item.image %}
                    <img id="" src="/{{ item.image }}" class="rounded-start" alt="..."
                         style="height: 100%; width: 100%; object-fit: cover;">
                {% else %}
                    <img id="" src="{% static 'images/logo.png' %}" class="rounded-start" alt="格物"
                         style="height: 100%; width: 100%; object-fit: cover;">
                {% endif %}
            </div>
            <div class="col-md-6" style="height: 100%;">
                <div class="card-body" style="height: 100%;">
                    <h1 class="card-title">{{ item.name }}</h1>
                    <br>
                    <p class="card-text">数量：{{ item.count }}</p>
                    <p class="card-text">状态：{{ item.status }}</p>
                    <p class="card-text">分类：{{ item.type }}</p>
                    <p class="card-text">是否为消耗品：
                        {% if item.is_consumable %}
                            是
                        {% else %}
                            否
                        {% endif %}
                    </p>
                    <p class="card-text">价格：{{ item.price }} 元</p>
                    {% if item.overdue %}
                        <p class="card-text">过期时间：{{ item.overdue|date:'Y-m-d' }}</p>
                    {% else %}
                        <p class="card-text">过期时间：无</p>
                    {% endif %}
                    {% if item.link %}
                        <p class="card-text">链接：{{ item.link }}</p>
                    {% else %}
                        <p class="card-text">链接：无</p>
                    {% endif %}
                    {% if item.description %}
                        <p class="card-text">描述：{{ item.description }}</p>
                    {% else %}
                        <p class="card-text">描述：无</p>
                    {% endif %}
                    <div class="d-flex justify-content-end" style="position: absolute; bottom: 10px; right: 10px;">
                        <a href="{% url 'items:item_modify' item_id=item.id %}" class="btn btn-primary"
                           style="margin: 5px">修改</a>
                        <a href="{% url 'items:item_remove' item_id=item.id %}" class="btn btn-warning" onclick="return confirm('确认移除该物品吗？');"
                           style="margin: 5px">移除</a>
                        <a href="{% url 'items:item_delete' item_id=item.id %}" class="btn btn-danger" onclick="return confirm('确认删除该物品吗？');"
                           style="margin: 5px">删除</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}